YOUTUBE_URL = "https://www.youtube.com"
SCROLL_AMOUNT_PX = 700
IMPLICIT_WAIT_SECONDS = 5

CHROME_DRIVER_MANUAL_PATH = r"C:\Users\Debajyoti\OneDrive\Desktop\practise\chromedriver-win32\chromedriver.exe"

HOVER_LISTEN_TIMEOUT_SECONDS = 3.5
GENERAL_LISTEN_TIMEOUT_SECONDS = 7
VIDEO_SELECTOR_ID = "video-title" 
SEARCH_BOX_NAME = "search_query"

TTS_ENGINE_RATE = 160
FUZZY_MATCH_THRESHOLD = 70